# goreleaser.yml
project_name: marill
build:
  binary: marill
  goos:
    - linux
  goarch:
    - amd64
  ldflags: -s -w -X main.version=v{{.Version}} -X main.commithash={{.Commit}} -X main.compiledate={{.Date}}
  hooks:
    post: make compress
snapshot:
  name_template: SNAPSHOT-{{.Commit}}
nfpm:
  homepage: https://marill.liam.sh/
  maintainer: Liam Stanley <me@liamstanley.io>
  description: Automated site testing utility.
  license: MIT
  formats:
    - deb
    - rpm
  bindir: /usr/bin
release:
  draft: true
