language: go
go:
  - 1.5
  - 1.6
  - 1.7
  - tip
script:
  - make test all
notifications:
  irc:
    channels:
      - "irc.byteirc.org#L"
    template:
      - "%{repository} #%{build_number} %{branch}/%{commit}: %{author} -- %{message} %{build_url}"
    on_success: change
    on_failure: change
    skip_join: true
